import type { CollectionConfig } from 'payload'

export const Orders: CollectionConfig = {
  slug: 'orders',
  admin: {
    useAsTitle: 'orderNumber',
    defaultColumns: ['orderNumber', 'status', 'totalUSD', 'isTest'],
  },
  fields: [
    {
      name: 'orderNumber',
      type: 'text',
      unique: true,
      admin: {
        readOnly: true, // Generated by hook default or externally
      },
    },
    {
      name: 'status',
      type: 'select',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Paid', value: 'paid' },
        { label: 'Canceled', value: 'canceled' },
      ],
      defaultValue: 'pending',
    },
    {
      name: 'pricingBasis',
      type: 'select',
      options: [
        { label: 'Member', value: 'member' },
        { label: 'Non-Member', value: 'non_member' },
        { label: 'Unknown', value: 'unknown' },
      ],
      defaultValue: 'unknown',
    },
    {
      name: 'stayAnon',
      type: 'checkbox',
      defaultValue: false,
    },
    {
      name: 'contact',
      type: 'relationship',
      relationTo: 'contacts',
    },
    {
      name: 'event',
      type: 'relationship',
      relationTo: 'events',
    },
    {
      name: 'campaign',
      type: 'relationship',
      relationTo: 'campaigns',
    },
    {
      name: 'isTest',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        position: 'sidebar',
      },
    },
  ],
  hooks: {
    beforeChange: [
      ({ data, operation }) => {
        if (operation === 'create' && !data.orderNumber) {
          // Simple unique generation: prefix + timestamp + random
          data.orderNumber = `ORD-${Date.now()}-${Math.floor(Math.random() * 1000)}`
        }
        return data
      },
    ],
  },
}
